# Generated by Django 3.1.7 on 2021-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='voivodeship',
            field=models.CharField(choices=[('Dolnośląskie', 'Dolnośląskie'), ('Opolskie', 'Opolskie'), ('Śląskie', 'Śląskie'), ('Wielkopolskie', 'Wielkopolskie')], default='qwe', max_length=100),
            preserve_default=False,
        ),
    ]
