# Generated by Django 3.1.7 on 2021-05-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacts_voivodeship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='voivodeship',
        ),
    ]
