# Generated by Django 3.1.7 on 2021-03-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210320_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Mieszkanie', 'Mieszkanie'), ('Dom', 'Dom'), ('Działka', 'Działka'), ('Lokal', 'Lokal')], default='Mieszkanie', max_length=100),
            preserve_default=False,
        ),
    ]
