# Generated by Django 3.1.7 on 2021-03-24 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='bedrooms',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='transaction',
        ),
    ]
