# Generated by Django 3.1.7 on 2021-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210324_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commission',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
