# Generated by Django 3.1.7 on 2021-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='voivodeship',
            field=models.CharField(choices=[('Dolnośląskie', 'Dolnośląskie'), ('Opolskie', 'Opolskie'), ('Śląskie', 'Śląskie'), ('Wielkopolskie', 'Wielkopolskie')], default='Dolnośląskie', max_length=100),
            preserve_default=False,
        ),
    ]
