# Generated by Django 3.1.7 on 2021-05-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_voivodeship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='voivodeship',
        ),
    ]
